server:
  port: 8044
  servlet:
    contextPath: /api

spring:
  data:
    db:
      host: localhost
      port: 27017
      database: kwetter-trendDB
  messaging:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
  profiles:
    active: mongoAtlas

#    mongodb+srv://kwetter:<password>@kwetter:dkh0o:mongodb:net/myFirstDatabase?retryWrites=true&w=majority: